/**
 * Renders the documents under `docs/` into `src/generated/index.ts` at build time. The Markdown
 * files are the single source of truth: nothing is copied into `site/`, and the generated module
 * is git-ignored.
 *
 * Sections and documents are discovered from the directory tree; `docs/README.md` contributes
 * order only. See docs/README.md, "How the menu is built".
 */
import { existsSync } from "node:fs";
import { copyFile, mkdir, readdir, readFile, rm, writeFile } from "node:fs/promises";
import { dirname, join, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { stripDocumentHeader, stripTableOfContents } from "../src/document.js";
import { renderMarkdown } from "../src/markdown.js";
import { buildNavigation, pagesOutsideNavigation, titleFromSlug } from "../src/navigation.js";
import { docPathToRoute, docPathToSection } from "../src/paths.js";
import type { DocPage, NavSection, SearchDocument, TocEntry } from "../src/types.js";

const scriptDirectory = dirname(fileURLToPath(import.meta.url));
const repositoryRoot = resolve(scriptDirectory, "../../../..");
const docsDirectory = join(repositoryRoot, "docs");
const generatedDirectory = resolve(scriptDirectory, "../src/generated");
const publicAssetsDirectory = resolve(scriptDirectory, "../../../apps/web/public/docs-assets");

const ASSET_BASE = "/docs-assets";
const IMAGE_EXTENSIONS = new Set([".jpg", ".jpeg", ".png", ".svg", ".webp", ".gif"]);
const WORDS_PER_MINUTE = 220;

async function main(): Promise<void> {
  if (!existsSync(docsDirectory)) {
    throw new Error(
      `Expected documentation at ${docsDirectory}. Run this from the site workspace.`,
    );
  }

  const markdownFiles = (await walk(docsDirectory)).filter((file) => file.endsWith(".md")).sort();
  const pages: DocPage[] = [];
  const searchDocuments: SearchDocument[] = [];

  for (const absolutePath of markdownFiles) {
    const sourcePath = toPosix(relative(repositoryRoot, absolutePath));
    const raw = await readFile(absolutePath, "utf8");
    const body = stripDocumentHeader(stripTableOfContents(raw));
    const { html, toc, text } = renderMarkdown(body, { sourcePath, assetBase: ASSET_BASE });

    // From the raw file: `body` has had exactly these removed.
    const title = extractTitle(raw, sourcePath);
    const summary = extractSummary(raw);
    const status = extractStatus(raw);
    const wordCount = text.split(/\s+/).filter(Boolean).length;

    const page: DocPage = {
      route: docPathToRoute(sourcePath),
      sourcePath,
      section: docPathToSection(sourcePath),
      title,
      summary,
      status,
      html,
      toc,
      wordCount,
      readingMinutes: Math.max(1, Math.round(wordCount / WORDS_PER_MINUTE)),
    };
    pages.push(page);

    searchDocuments.push({
      id: page.route,
      route: page.route,
      title,
      section: page.section ? titleFromSlug(page.section) : "Documentation",
      headings: toc.map((entry: TocEntry) => entry.text).join(" "),
      body: text,
    });
  }

  const navigation = buildNavigation(
    pages,
    await readFile(join(docsDirectory, "README.md"), "utf8"),
  );
  await copyImages(markdownFiles);
  await writeGenerated(pages, navigation, searchDocuments);

  for (const page of pagesOutsideNavigation(pages, navigation)) {
    console.log(`[content] ${page.sourcePath} is reachable at ${page.route}, not in the sidebar.`);
  }
  console.log(`[content] ${pages.length} documents, ${navigation.length} sections.`);
}

async function copyImages(markdownFiles: readonly string[]): Promise<void> {
  const docFiles = await walk(docsDirectory);
  const images = docFiles.filter((file) =>
    IMAGE_EXTENSIONS.has(file.slice(file.lastIndexOf(".")).toLowerCase()),
  );

  await rm(publicAssetsDirectory, { recursive: true, force: true });
  for (const image of images) {
    const target = join(publicAssetsDirectory, relative(docsDirectory, image));
    await mkdir(dirname(target), { recursive: true });
    await copyFile(image, target);
  }
  void markdownFiles;
  console.log(`[content] ${images.length} images copied to public/docs-assets.`);
}

async function writeGenerated(
  pages: readonly DocPage[],
  navigation: readonly NavSection[],
  searchDocuments: readonly SearchDocument[],
): Promise<void> {
  await mkdir(generatedDirectory, { recursive: true });

  const module = `// Generated by packages/content/scripts/generate.ts. Do not edit.
import type { DocPage, NavSection, SearchDocument } from "../types.js";

export const pages: readonly DocPage[] = ${JSON.stringify(pages, null, 2)};

export const navigation: readonly NavSection[] = ${JSON.stringify(navigation, null, 2)};

export const searchDocuments: readonly SearchDocument[] = ${JSON.stringify(searchDocuments, null, 2)};

export const docRoutes: readonly string[] = ${JSON.stringify(
    pages.map((page) => page.route),
    null,
    2,
  )};

export function findPage(route: string): DocPage | undefined {
  return pages.find((page) => page.route === route);
}
`;

  await writeFile(join(generatedDirectory, "index.ts"), module, "utf8");
}

async function walk(directory: string): Promise<string[]> {
  const entries = await readdir(directory, { withFileTypes: true });
  const files = await Promise.all(
    entries.map(async (entry) => {
      const full = join(directory, entry.name);
      return entry.isDirectory() ? walk(full) : [full];
    }),
  );
  return files.flat();
}

function extractTitle(markdown: string, sourcePath: string): string {
  const match = markdown.match(/^#\s+(.+)$/m);
  if (match?.[1]) return match[1].trim();
  // architecture/README.md opens with its table of contents rather than a title.
  const section = docPathToSection(sourcePath);
  return section ? titleFromSlug(section) : "Documentation";
}

function extractSummary(markdown: string): string {
  const body = markdown
    .replace(/^#\s+.+$/m, "")
    .replace(/^\*\*Status:\*\*.*$/gm, "")
    .replace(/^\*\*Companion[^*]*\*\*.*$/gm, "")
    .replace(/^\*\*Deliverable:\*\*.*$/gm, "");

  for (const block of body.split(/\n{2,}/)) {
    const line = block.trim();
    if (!line || line.startsWith("#") || line.startsWith("|") || line.startsWith("```")) continue;
    if (line.startsWith("---") || line.startsWith(">") || /^\d+\.\s/.test(line)) continue;
    if (line.startsWith("-") || line.startsWith("*")) continue;
    return stripInlineMarkdown(line).slice(0, 280);
  }
  return "";
}

function extractStatus(markdown: string): string | null {
  const match = markdown.match(/^\*\*Status:\*\*\s*(.+)$/m);
  return match?.[1] ? stripInlineMarkdown(match[1].trim()) : null;
}

function stripInlineMarkdown(value: string): string {
  return value
    .replace(/\[([^\]]+)\]\([^)]*\)/g, "$1")
    .replace(/[*_`]/g, "")
    .replace(/\s+/g, " ")
    .trim();
}

function toPosix(value: string): string {
  return value.split(/[\\/]/).join("/");
}

await main();
